### ISSUE TITLE
[ENHANCEMENT] Now.GG/Play.GG support

### ISSUE THREAD

**Issue by MattTheTekie** [mistertest/cloud-choice#1]
[ENHANCEMENT] Now.GG/Play.GG support

**Comment by MattTheTekie** [comment]
Do you think it could be a thing later down the line?

**Comment by mistertest** [comment]
hello @AstaFatherSatan I can build a apk for Android TV on nvidia shield and google play tv. Why not. Perhaps after the new xcloud shield version, I am now working on this version.

**Comment by MattTheTekie** [comment]
ok
